### ISSUE TITLE
Detection of MS Clarity is broken again (former issue 265)

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [whotracksme/whotracks.me#285]
See for example https://www.cora.fr/ 

![image](https://user-images.githubusercontent.com/282461/173522826-332afb68-4aba-46ba-8dae-c4eb2cefdbe5.png)

![image](https://user-images.githubusercontent.com/282461/173523065-070ed757-41a9-4d5f-a382-f5b3f9091d64.png)

https://www.clarity.ms/tag/uet/19004077 
https://n.clarity.ms/s/0.6.34/clarity.js
https://n.clarity.ms/collect

Thanks for your attention

**Comment by philipp-classen** [comment]
Should be detected now:

![2022-06-29-ms-clarity](https://user-images.githubusercontent.com/1616509/176430798-67ed5c0b-332d-4dda-9bc2-d7799bcda8ac.png)

Thanks for reporting!

**Comment by googleanalyticsresoneo** [comment]
@philipp-classen 

I have been waiting a few days to be sure the update had been pushed live, but I still don't see it as detected 

https://www.clarity.ms/tag/uet/19004077
https://www.clarity.ms/eus2-b/s/0.6.35/clarity.js
https://e.clarity.ms/collect


![2022-07-04 11_44_26-cora - Magasin, Drive, courses en ligne et livraison à domicile Clarity](https://user-images.githubusercontent.com/282461/177129328-20a96e58-0ffe-4d9b-b86c-6ed68345dcfa.png)

![image](https://user-images.githubusercontent.com/282461/177129592-32c933af-26f5-4e68-b107-515dc9056b9a.png)

What could help understand what is the issue there ??

Regards

**Comment by philipp-classen** [comment]
From what I see, there are only request to MS Clarity on the page once you granted consent. Depending how Ghostery is configured, the consent dialog might be blocked. One way that works for me, is to temporarily pause Ghostery. Then it will not block but only reports trackers. After a page reload, there should be a consent dialog. Once you allow it, there should be requests coming from MS Clarity, which should then be reported in the Ghostery UI.

To make sure that you got the latest version of the patterns, you can also try it in a fresh browser profile. But that should not be necessary, since your existing one should have been updated already.

**Comment by philipp-classen** [comment]
We just found a bug with the update mechanism:
https://github.com/ghostery/ghostery-extension/issues/838

That is very likely the explanation for the problem. A temporary workaround is to clear browser caches (for details can be found in the issue). We are working on a fix for the next Ghostery release.

**Comment by googleanalyticsresoneo** [comment]
I was able to force the database update and now it's properly detected indeed

That update issue sounds serious

![2022-08-26 15_36_14-](https://user-images.githubusercontent.com/282461/186937871-c0880402-4f60-4f8d-91c7-2007165e5628.png)
![2022-08-26 15_39_00-](https://user-images.githubusercontent.com/282461/186937883-4c956333-3c51-469c-bd09-d19b095366c5.png)

**Comment by philipp-classen** [comment]
Indeed, it is a nasty bug. We merged a fix for it, today: https://github.com/ghostery/ghostery-extension/pull/846

I'll close this one for now. Thank you for confirming!
